#!/usr/bin/env bash
# Script that configures Nginx server with a custom 404 error page

# Update package index
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx with 301 redirect for /redirect_me
sed -i '/location \/ {/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Configure custom 404 error page
sed -i '/location \/ {/a\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Start nginx service (without using systemctl)
service nginx start

# Enable nginx to start on boot
update-rc.d nginx enable
